# Generated by Django 3.2.8 on 2021-11-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20211105_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='date_vistied',
            new_name='date_visited',
        ),
    ]
